### ISSUE TITLE
custom classes

### ISSUE THREAD

**Issue by Maxfashko** [qijiezhao/M2Det#37]
Hi! Tell me please, how can I train your model on my data set with a different number of classes?
I created a dataset the same as the directory structure of the dasset PASCAL_VOC.
Then, I changed the path to the dataset and the number of classes in the configuration file.
`num_classes = 1`

But, i get an error:

> /opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [273,0,0], thread: [353,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [79,0,0], thread: [99,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [79,0,0], thread: [483,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [457,0,0], thread: [195,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [80,0,0], thread: [325,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [81,0,0], thread: [197,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [274,0,0], thread: [225,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [330,0,0], thread: [395,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [145,0,0], thread: [423,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [399,0,0], thread: [105,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [399,0,0], thread: [107,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [397,0,0], thread: [361,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [397,0,0], thread: [363,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [407,0,0], thread: [103,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [453,0,0], thread: [263,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [458,0,0], thread: [487,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [459,0,0], thread: [323,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [82,0,0], thread: [69,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [265,0,0], thread: [97,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [82,0,0], thread: [453,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [400,0,0], thread: [301,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [400,0,0], thread: [303,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [78,0,0], thread: [227,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [78,0,0], thread: [233,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [456,0,0], thread: [323,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [458,0,0], thread: [67,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [458,0,0], thread: [451,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [271,0,0], thread: [225,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [204,0,0], thread: [147,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [204,0,0], thread: [149,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [272,0,0], thread: [481,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [139,0,0], thread: [357,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [396,0,0], thread: [107,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [396,0,0], thread: [489,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [396,0,0], thread: [491,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [79,0,0], thread: [453,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [74,0,0], thread: [421,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [74,0,0], thread: [433,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [401,0,0], thread: [173,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [401,0,0], thread: [175,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [398,0,0], thread: [233,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [398,0,0], thread: [235,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [460,0,0], thread: [237,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [117,0,0], thread: [509,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [181,0,0], thread: [489,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [137,0,0], thread: [179,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [391,0,0], thread: [433,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [71,0,0], thread: [473,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [150,0,0], thread: [209,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [150,0,0], thread: [221,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [268,0,0], thread: [153,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [372,0,0], thread: [431,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [140,0,0], thread: [229,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [267,0,0], thread: [279,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [267,0,0], thread: [281,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [267,0,0], thread: [285,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [309,0,0], thread: [473,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [451,0,0], thread: [505,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [271,0,0], thread: [223,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [203,0,0], thread: [277,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [399,0,0], thread: [45,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [399,0,0], thread: [47,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [399,0,0], thread: [429,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [399,0,0], thread: [431,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [455,0,0], thread: [433,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [149,0,0], thread: [349,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [399,0,0], thread: [83,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [182,0,0], thread: [169,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [77,0,0], thread: [355,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [77,0,0], thread: [361,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [456,0,0], thread: [305,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [282,0,0], thread: [479,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [151,0,0], thread: [93,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [151,0,0], thread: [477,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [273,0,0], thread: [351,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [396,0,0], thread: [269,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [394,0,0], thread: [15,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [394,0,0], thread: [21,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [74,0,0], thread: [53,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [141,0,0], thread: [503,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [79,0,0], thread: [87,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [274,0,0], thread: [223,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [454,0,0], thread: [369,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [140,0,0], thread: [211,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [139,0,0], thread: [339,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [272,0,0], thread: [97,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [272,0,0], thread: [121,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [141,0,0], thread: [101,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [141,0,0], thread: [119,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [272,0,0], thread: [95,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [272,0,0], thread: [479,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [397,0,0], thread: [339,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [266,0,0], thread: [409,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [31,0,0], thread: [445,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [31,0,0], thread: [49,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch-nightly_1551849226410/work/aten/src/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 2]: block: [31,0,0], thread: [61,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
Traceback (most recent call last):
  File "train.py", line 104, in <module>
    loss_l, loss_c = criterion(out, priors, targets)
  File "/home/maksim/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/mnt/data/code/object_detection/M2Det/layers/modules/multibox_loss.py", line 95, in forward
    loss_c[pos.view(-1,1)] = 0 # filter out pos boxes for now
RuntimeError: copy_if failed to synchronize: device-side assert triggered

I would be grateful for any help

**Comment by dshahrokhian** [comment]
Just a random thought, did not try it myself: `num_classes=2`, since '__background__' is already a class.

**Comment by Maxfashko** [comment]
@dshahrokhian thank, it helped.
I have one more question. My model trained 10 epoch (600 image). I run demo.py script and see than bbox aligned randomly over image. What shall i do? Or is this a normal situation and you need to train more time?

**Comment by Maxfashko** [comment]
![image](https://user-images.githubusercontent.com/11171626/54816211-49fc0700-4cc6-11e9-9fe6-e348812a42c4.png)

> pos:(4.4,-49.1,156.7,199.6), ids:person, score:1.000
pos:(119.9,-47.5,279.2,201.6), ids:person, score:1.000
pos:(1748.8,-38.1,1903.9,212.6), ids:person, score:1.000
pos:(18.3,485.6,142.4,695.9), ids:person, score:1.000
pos:(70.4,538.3,208.6,767.5), ids:person, score:1.000
pos:(185.5,525.4,332.5,771.1), ids:person, score:1.000
pos:(302.0,515.1,455.5,770.1), ids:person, score:1.000
pos:(122.0,592.4,278.3,839.3), ids:person, score:1.000
pos:(19.2,632.0,167.2,871.7), ids:person, score:1.000
pos:(235.8,613.2,399.0,877.5), ids:person, score:1.000
pos:(355.3,608.2,513.1,884.7), ids:person, score:1.000
pos:(480.6,646.6,637.0,931.0), ids:person, score:1.000
pos:(1191.1,629.0,1369.8,917.5), ids:person, score:1.000
pos:(602.5,688.8,752.3,965.3), ids:person, score:1.000
pos:(727.8,688.2,874.3,966.8), ids:person, score:1.000
pos:(850.8,681.3,1000.4,966.4), ids:person, score:1.000
pos:(958.8,673.6,1123.7,962.8), ids:person, score:1.000
pos:(1072.2,670.2,1242.4,957.1), ids:person, score:1.000
pos:(1310.2,669.1,1483.1,953.0), ids:person, score:1.000
pos:(1438.5,673.7,1605.4,966.8), ids:person, score:1.000
pos:(62.7,733.4,233.6,950.0), ids:person, score:1.000
pos:(299.5,729.1,474.0,963.3), ids:person, score:1.000
pos:(412.1,729.8,578.8,992.9), ids:person, score:1.000
pos:(1574.7,737.8,1724.7,990.1), ids:person, score:1.000
pos:(1748.5,732.4,1903.9,1004.1), ids:person, score:1.000
pos:(203.6,766.6,362.1,964.2), ids:person, score:1.000
pos:(785.6,755.0,941.1,1028.1), ids:person, score:1.000
pos:(530.8,772.5,697.8,1041.7), ids:person, score:1.000
pos:(654.1,772.0,817.2,1048.8), ids:person, score:1.000
pos:(901.4,767.8,1058.5,1053.1), ids:person, score:1.000
pos:(1020.6,767.3,1181.0,1053.5), ids:person, score:1.000
pos:(1142.7,776.6,1299.8,1046.9), ids:person, score:1.000
pos:(1269.4,783.5,1420.9,1040.9), ids:person, score:1.000
pos:(1403.6,792.3,1547.0,1031.9), ids:person, score:1.000
pos:(1522.8,705.5,1652.6,1089.5), ids:person, score:1.000
pos:(1649.7,791.9,1779.5,1030.4), ids:person, score:1.000
pos:(-25.3,852.3,136.6,1073.3), ids:person, score:1.000
pos:(112.4,779.8,283.6,1116.6), ids:person, score:1.000
pos:(369.2,794.7,514.0,1157.2), ids:person, score:1.000
pos:(1224.7,771.4,1345.4,1168.1), ids:person, score:1.000
pos:(241.4,818.6,402.8,1182.6), ids:person, score:1.000

**Comment by rw1995** [comment]
> ![image](https://user-images.githubusercontent.com/11171626/54816211-49fc0700-4cc6-11e9-9fe6-e348812a42c4.png)
> 
> > pos:(4.4,-49.1,156.7,199.6), ids:person, score:1.000
> > pos:(119.9,-47.5,279.2,201.6), ids:person, score:1.000
> > pos:(1748.8,-38.1,1903.9,212.6), ids:person, score:1.000
> > pos:(18.3,485.6,142.4,695.9), ids:person, score:1.000
> > pos:(70.4,538.3,208.6,767.5), ids:person, score:1.000
> > pos:(185.5,525.4,332.5,771.1), ids:person, score:1.000
> > pos:(302.0,515.1,455.5,770.1), ids:person, score:1.000
> > pos:(122.0,592.4,278.3,839.3), ids:person, score:1.000
> > pos:(19.2,632.0,167.2,871.7), ids:person, score:1.000
> > pos:(235.8,613.2,399.0,877.5), ids:person, score:1.000
> > pos:(355.3,608.2,513.1,884.7), ids:person, score:1.000
> > pos:(480.6,646.6,637.0,931.0), ids:person, score:1.000
> > pos:(1191.1,629.0,1369.8,917.5), ids:person, score:1.000
> > pos:(602.5,688.8,752.3,965.3), ids:person, score:1.000
> > pos:(727.8,688.2,874.3,966.8), ids:person, score:1.000
> > pos:(850.8,681.3,1000.4,966.4), ids:person, score:1.000
> > pos:(958.8,673.6,1123.7,962.8), ids:person, score:1.000
> > pos:(1072.2,670.2,1242.4,957.1), ids:person, score:1.000
> > pos:(1310.2,669.1,1483.1,953.0), ids:person, score:1.000
> > pos:(1438.5,673.7,1605.4,966.8), ids:person, score:1.000
> > pos:(62.7,733.4,233.6,950.0), ids:person, score:1.000
> > pos:(299.5,729.1,474.0,963.3), ids:person, score:1.000
> > pos:(412.1,729.8,578.8,992.9), ids:person, score:1.000
> > pos:(1574.7,737.8,1724.7,990.1), ids:person, score:1.000
> > pos:(1748.5,732.4,1903.9,1004.1), ids:person, score:1.000
> > pos:(203.6,766.6,362.1,964.2), ids:person, score:1.000
> > pos:(785.6,755.0,941.1,1028.1), ids:person, score:1.000
> > pos:(530.8,772.5,697.8,1041.7), ids:person, score:1.000
> > pos:(654.1,772.0,817.2,1048.8), ids:person, score:1.000
> > pos:(901.4,767.8,1058.5,1053.1), ids:person, score:1.000
> > pos:(1020.6,767.3,1181.0,1053.5), ids:person, score:1.000
> > pos:(1142.7,776.6,1299.8,1046.9), ids:person, score:1.000
> > pos:(1269.4,783.5,1420.9,1040.9), ids:person, score:1.000
> > pos:(1403.6,792.3,1547.0,1031.9), ids:person, score:1.000
> > pos:(1522.8,705.5,1652.6,1089.5), ids:person, score:1.000
> > pos:(1649.7,791.9,1779.5,1030.4), ids:person, score:1.000
> > pos:(-25.3,852.3,136.6,1073.3), ids:person, score:1.000
> > pos:(112.4,779.8,283.6,1116.6), ids:person, score:1.000
> > pos:(369.2,794.7,514.0,1157.2), ids:person, score:1.000
> > pos:(1224.7,771.4,1345.4,1168.1), ids:person, score:1.000
> > pos:(241.4,818.6,402.8,1182.6), ids:person, score:1.000
> 
> Confidence 1.0 on all objects - this is at least strange :)

can u help me? when i run the demo.py following the progress ,but have a wrong .
I do **sh make.sh** and **python demo.py -c=configs/m2det512_vgg.py -m=weights/m2det512_vgg.pth --show**
but  the result is 

The Anchor info: 
{'variance': [0.1, 0.2], 'min_sizes': [30.72, 76.8, 168.96, 261.12, 353.28, 445.44], 'aspect_ratios': [[2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3]], 'clip': True, 'feature_maps': [64, 32, 16, 8, 4, 2], 'min_dim': 512, 'max_sizes': [76.8, 168.96, 261.12, 353.28, 445.44, 537.6], 'steps': [8, 16, 32, 64, 128, 256]}
===> Constructing M2Det model
Loading resume network...
===> Finished constructing and loading model
<class 'm2det.M2Det'>
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
Traceback (most recent call last):
  File "demo.py", line 113, in <module>
    out = net(img)
  File "/home/csy/anaconda3/envs/pytorch0.4.1/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/csy/M2Det/m2det.py", line 106, in forward
    x = self.base[k](x)
  File "/home/csy/anaconda3/envs/pytorch0.4.1/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/csy/anaconda3/envs/pytorch0.4.1/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 301, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:663

how can you run  the demo.py? do you modified some locations?I will be grateful to you 
@Maxfashko

**Comment by rw1995** [comment]
> > ![image](https://user-images.githubusercontent.com/11171626/54816211-49fc0700-4cc6-11e9-9fe6-e348812a42c4.png)
> > > pos:(4.4,-49.1,156.7,199.6), ids:person, score:1.000
> > > pos:(119.9,-47.5,279.2,201.6), ids:person, score:1.000
> > > pos:(1748.8,-38.1,1903.9,212.6), ids:person, score:1.000
> > > pos:(18.3,485.6,142.4,695.9), ids:person, score:1.000
> > > pos:(70.4,538.3,208.6,767.5), ids:person, score:1.000
> > > pos:(185.5,525.4,332.5,771.1), ids:person, score:1.000
> > > pos:(302.0,515.1,455.5,770.1), ids:person, score:1.000
> > > pos:(122.0,592.4,278.3,839.3), ids:person, score:1.000
> > > pos:(19.2,632.0,167.2,871.7), ids:person, score:1.000
> > > pos:(235.8,613.2,399.0,877.5), ids:person, score:1.000
> > > pos:(355.3,608.2,513.1,884.7), ids:person, score:1.000
> > > pos:(480.6,646.6,637.0,931.0), ids:person, score:1.000
> > > pos:(1191.1,629.0,1369.8,917.5), ids:person, score:1.000
> > > pos:(602.5,688.8,752.3,965.3), ids:person, score:1.000
> > > pos:(727.8,688.2,874.3,966.8), ids:person, score:1.000
> > > pos:(850.8,681.3,1000.4,966.4), ids:person, score:1.000
> > > pos:(958.8,673.6,1123.7,962.8), ids:person, score:1.000
> > > pos:(1072.2,670.2,1242.4,957.1), ids:person, score:1.000
> > > pos:(1310.2,669.1,1483.1,953.0), ids:person, score:1.000
> > > pos:(1438.5,673.7,1605.4,966.8), ids:person, score:1.000
> > > pos:(62.7,733.4,233.6,950.0), ids:person, score:1.000
> > > pos:(299.5,729.1,474.0,963.3), ids:person, score:1.000
> > > pos:(412.1,729.8,578.8,992.9), ids:person, score:1.000
> > > pos:(1574.7,737.8,1724.7,990.1), ids:person, score:1.000
> > > pos:(1748.5,732.4,1903.9,1004.1), ids:person, score:1.000
> > > pos:(203.6,766.6,362.1,964.2), ids:person, score:1.000
> > > pos:(785.6,755.0,941.1,1028.1), ids:person, score:1.000
> > > pos:(530.8,772.5,697.8,1041.7), ids:person, score:1.000
> > > pos:(654.1,772.0,817.2,1048.8), ids:person, score:1.000
> > > pos:(901.4,767.8,1058.5,1053.1), ids:person, score:1.000
> > > pos:(1020.6,767.3,1181.0,1053.5), ids:person, score:1.000
> > > pos:(1142.7,776.6,1299.8,1046.9), ids:person, score:1.000
> > > pos:(1269.4,783.5,1420.9,1040.9), ids:person, score:1.000
> > > pos:(1403.6,792.3,1547.0,1031.9), ids:person, score:1.000
> > > pos:(1522.8,705.5,1652.6,1089.5), ids:person, score:1.000
> > > pos:(1649.7,791.9,1779.5,1030.4), ids:person, score:1.000
> > > pos:(-25.3,852.3,136.6,1073.3), ids:person, score:1.000
> > > pos:(112.4,779.8,283.6,1116.6), ids:person, score:1.000
> > > pos:(369.2,794.7,514.0,1157.2), ids:person, score:1.000
> > > pos:(1224.7,771.4,1345.4,1168.1), ids:person, score:1.000
> > > pos:(241.4,818.6,402.8,1182.6), ids:person, score:1.000
> > 
> > 
> > Confidence 1.0 on all objects - this is at least strange :)
> 
> can u help me? when i run the demo.py following the progress ,but have a wrong .
> I do **sh make.sh** and **python demo.py -c=configs/m2det512_vgg.py -m=weights/m2det512_vgg.pth --show**
> but the result is
> 
> The Anchor info:
> {'variance': [0.1, 0.2], 'min_sizes': [30.72, 76.8, 168.96, 261.12, 353.28, 445.44], 'aspect_ratios': [[2, 3], [2, 3], [2, 3], [2, 3], [2, 3], [2, 3]], 'clip': True, 'feature_maps': [64, 32, 16, 8, 4, 2], 'min_dim': 512, 'max_sizes': [76.8, 168.96, 261.12, 353.28, 445.44, 537.6], 'steps': [8, 16, 32, 64, 128, 256]}
> ===> Constructing M2Det model
> Loading resume network...
> ===> Finished constructing and loading model
> <class 'm2det.M2Det'>
> THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=663 error=11 : invalid argument
> Traceback (most recent call last):
> File "demo.py", line 113, in 
> out = net(img)
> File "/home/csy/anaconda3/envs/pytorch0.4.1/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/csy/M2Det/m2det.py", line 106, in forward
> x = self.base[k](x)
> File "/home/csy/anaconda3/envs/pytorch0.4.1/lib/python3.5/site-packages/torch/nn/modules/module.py", line 477, in **call**
> result = self.forward(*input, **kwargs)
> File "/home/csy/anaconda3/envs/pytorch0.4.1/lib/python3.5/site-packages/torch/nn/modules/conv.py", line 301, in forward
> self.padding, self.dilation, self.groups)
> RuntimeError: cuda runtime error (11) : invalid argument at /pytorch/aten/src/THC/THCGeneral.cpp:663
> 
> how can you run the demo.py? do you modified some locations?I will be grateful to you
> @Maxfashko

ok，i solve it .just my environment about pytorch is wrong .

**Comment by dshahrokhian** [comment]
Did it work with pytorch 0.4?

**Comment by Maxfashko** [comment]
@dshahrokhian no, i use pytorch 1.0

**Comment by dshahrokhian** [comment]
I meant @rw1995, as it seems to work for him now.

**Comment by y-shirai-r** [comment]
@Maxfashko 
Did you change rgb_means on configuration file at your training?
I think if we want to use own datasets then, we should make this using all of image data.

or Can I ignore the change of rgb_means on training?
Thanks.

**Comment by ufohuang98** [comment]
@Maxfashko 
![91_m2det](https://user-images.githubusercontent.com/14228192/55372749-c9e36600-553d-11e9-9875-e0392c64871c.jpg)
I have the same issue ,would you please tell me how did you fixed it?
I use pytorch 0.4.1, coco dota format and trained 26 epoch.

**Comment by Maxfashko** [comment]
@ufohuang98 I could not fix this problem. It seems the developers need to pay attention to this problem, and explain why this is happening and how to solve it. @dshahrokhian we can hope to get clear explanations from you about this problem? Or do you prefer to leave us alone with this problem? :)

**Comment by Xiehuaiqi** [comment]
I meet the same question to train one class.if you solve ,please help me

**Comment by Maxfashko** [comment]
@Xiehuaiqi  I stopped trying to make the code work that is obviously not working :)
The author chose to ignore our questions. Either @dshahrokhian is not competent, or my assumption is true - the code is not working :)

**Comment by DeqiangWang** [comment]
@dshahrokhian @Maxfashko  I also meet the the problem.....and I dont know how to solve.
I retrain VOC0712, and get good results, but when train my dataset for one class, get random result.

**Comment by lonl** [comment]
@dshahrokhian @Maxfashko @DeqiangWang @Xiehuaiqi @ufohuang98 @rw1995 maybe you should adjust the weights between "loss_l" and "loss_c", you could find "loss = loss_l + loss_c" in "train.py" of this project, and you can introduce a parameter lambda to change the loss, like "loss = loss_l + 0.1*loss_c", finally, you may get the correct results~

**Comment by taehyunzzz** [comment]
@lonl  Hi, you mentioned weighting the 2 loss values as a possible resolution. Did this work out for you?

**Comment by lonl** [comment]
@taehyunzzz, I have conducted this way to try to solve the problem, however, some pics still have many error bounding boxes, and maybe this way could not work ~
